apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-a-read-only
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: {{ .Values.userA }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-b-write
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: {{ .Values.userB }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: write-role
  apiGroup: rbac.authorization.k8s.io
