{{- range .Values.readOnlyUsers }}
# read-only
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-read-only
  namespace: {{ $.Values.namespace }}
subjects:
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}

{{- range .Values.writeUsers }}
# write
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-write
  namespace: {{ $.Values.namespace }}
subjects:
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: write-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
