# read-only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: read-only-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]

---
# write
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "update"]
