{{- range .Values.serviceAccounts }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ $.Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
